Repository textlint-rule/sentence-splitter, pull requests merged in 2023-11, with the labels that each got.

#45 match uppercase non-english letters too
  src/parser/AbbrMarker.ts
  test/fixtures/1-sentence--nesting-pair-mark/output.json
  test/fixtures/recognize-foreign-uppercase-characters/_input.md
  test/fixtures/recognize-foreign-uppercase-characters/input.json
  test/fixtures/recognize-foreign-uppercase-characters/output.json
Labels: Type: Feature

#47 fix(deps): update @textlint/ast-node-types
  .github/workflows/test.yml
  package.json
  src/sentence-splitter.ts
  test/sentence-splitter-test.ts
  tsconfig.cjs.json
  tsconfig.json
  yarn.lock
Labels: Type: Bug

#49 BREAKING CHANGE: Drop Node.js 16 support
  .github/workflows/test.yml
  package.json
  tsconfig.json
Labels: Type: Breaking Change
